[package]
name = "mindbase"
version = "0.0.1"
authors = ["Daniel Norman <daniel@danielnorman.net>"]
edition = "2018"
license = "MIT/Apache-2.0"
readme = "README.md"
repository = "https://github.com/mindbeam/mindbase"
# build = "build.rs"

[dependencies]
typenum = "1.11.2"
inverted-index-util = "0.0.5"
base64 = "0.11.0"
tempfile = "3.1.0"
serde = { version = "1.0.104", features = ["derive"] }
serde_json = "1.0.48"
bincode = "1.2.1"
sled = "0.31.0"
rand="0.6"
sha2 = "0.8"
ed25519-dalek = { version = "0.9", features = ["serde"] }
rusty_ulid = "0.9.3"
rustyline = "6.0.0"
chrono = { version = "0.4.10", features = ["serde"] }
# capnp = "0.12.1"
regex="1.3.6"
lazy_static="1.4.0"

[build-dependencies]
capnpc = "0.12.1"